import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import logo from '../../images/svg/logo.svg'
// import favicon from '../../public/favicon.png'

export function Header({ lang = 'uk', title = '' }) {
  console.log('Header', lang)

  let [enActive, ruActive, ukActive] = ['', '', '']
  let [keywords, description, consultButton, menuItems, practicesItems, offices] = ['', '', '', [], [], []]
  switch (lang) {
    case 'ru':
      ruActive = ' active'
      keywords = 'Адвокат,Адвокат Киев,Консультации'
      description = 'Адвокатское объединение «Global Barristers» ≡ Адвокат Киев ≡ Консультации'
      consultButton = 'Заказать консультацию'
      menuItems = ['О нас', 'Наша команда', 'Отрасли', 'Города', 'Бизнес решения', 'Партнеры', 'Контакты']
      practicesItems = [
        'Уголовное Право',
        'Хозяйственное Право',
        'Семейное Право',
        'Налоговое Право',
        'Гражданское Право',
        'Таможенное Право',
        'Иммиграционное Законодательство',
        'Споры с банком',
        'Автомобильное Право',
      ]
      offices = [
        'Офис в Киеве',
        'Офис в Харькове',
        'Офис в Одессе',
        'Офис в Днепре',
        'Офис в Запорожье',
        'Офис в Кривом Роге',
      ]
      break

    case 'en':
      enActive = ' active'
      keywords = 'Lawyer, Lawyer Kiev, Consulting'
      description = 'Law Firm «Global Barristers» ≡ Kyiv Lawyer ≡ Consultations'
      consultButton = 'Request consultation'
      menuItems = ['About us', 'Our team', 'Departments', 'Cities', 'Business solutions', 'Partners', 'Contacts']
      practicesItems = [
        'Criminal Law',
        'Commercial Law',
        'Family Law',
        'Tax Law',
        'Civil Law',
        'Customs Law',
        'Immigration Law',
        'Bank Disputes',
        'Car Law',
      ]
      offices = [
        'Office in Kyiv',
        'Office in Kharkiv',
        'Office in Odessa',
        'Office in the Dnieper',
        'Office in Zaporozhye',
        'Office in Kryvyi Rih',
      ]
      break

    default:
      console.log('default')
      ukActive = ' active'
      keywords = 'Адвокат,Адвокат Київ,Консультації'
      description = "Адвокатське об'єднання «Global Barristers» ≡ Адвокат Київ ≡ Консультації"
      consultButton = 'Замовити консультацію'
      menuItems = ['Про нас', 'Наша команда', 'Галузі', 'Міста', 'Бізнес рішення', 'Партнери', 'Контакти']
      practicesItems = [
        'Кримінальне Право',
        'Господарське Право',
        'Сімейне Право',
        'Податкове Право',
        'Цивільне Право',
        'Митне Право',
        'Імміграційне Законодавство',
        'Спори з банком',
        'Автомобільне Право',
      ]
      offices = [
        'Офіс в Києві',
        'Офіс в Харкові',
        'Офіс в Одесі',
        'Офіс в Дніпрі',
        'Офіс в Запоріжжі',
        'Офіс в Кривому Розі',
      ]
      break
  }

  return (
    <>
      <Head>
        <title>{'«Global Barristers» ≡ ' + title}</title>
        <meta name='viewport' content='Generated by create next app' />
        <meta charSet='UTF-8' />
        <meta name='keywords' content={keywords} />
        <meta name='description' content={description} />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <header>
        <section className='header__pre'></section>
        <section className='header'>
          <div className='top-menu'>
            <div className='top-menu__container container'>
              <div className='top-menu__numbers'>
                <Link href='tel:+38 (099) 603 24 54'>
                  <a className='top-menu__link'>+38 (099) 603 24 54</a>
                </Link>
                <Link href='tel:+38 (098) 235 02 70'>
                  <a className='top-menu__link'>+38 (098) 235 02 70</a>
                </Link>
              </div>

              <div className='lang'>
                <div className='lang__wrapper'>
                  <Link href='/en/'>
                    <a className={'lang__link lang_en' + enActive}> en </a>
                  </Link>
                  <Link href='/ru/'>
                    <a className={'lang__link lang_en' + ruActive}> ru </a>
                  </Link>
                  <Link href='/uk/'>
                    <a className={'lang__link lang_en' + ukActive}> uk </a>
                  </Link>
                </div>
              </div>
            </div>
          </div>

          <nav className='navigation'>
            <div className='navigation__container container'>
              <div className='navigation__logo'>
                <Link href={'/' + lang + '/'}>
                  <a>
                    <Image
                      className='navigation__logo-img'
                      src={logo.src}
                      alt='Global Barristers'
                      width={306.531}
                      height={45}
                    />
                  </a>
                </Link>
              </div>
              <div className='menu'>
                <ul id={'menu-' + lang + '/'} className='menu__list'>
                  <li className='menu__item'>
                    <Link href={'/about-us/' + lang + '/'}>
                      <a>{menuItems[0]}</a>
                    </Link>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/our-team/' + lang + '/'}>
                      <a>{menuItems[1]}</a>
                    </Link>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/practices/' + lang + '/'}>
                      <a>{menuItems[2]}</a>
                    </Link>
                    <ul className='sub-menu'>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/criminal-law/' + lang + '/'}>
                          <a>{practicesItems[0]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/economic-law/' + lang + '/'}>
                          <a>{practicesItems[1]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/family-law/' + lang + '/'}>
                          <a>{practicesItems[2]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/tax-_law/' + lang + '/'}>
                          <a>{practicesItems[3]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/civil-law/' + lang + '/'}>
                          <a>{practicesItems[4]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/customs-law/' + lang + '/'}>
                          <a>{practicesItems[5]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/immigration-legislation/' + lang + '/'}>
                          <a>{practicesItems[6]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/banking-disputes/' + lang + '/'}>
                          <a>{practicesItems[7]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/practices/auto-law/' + lang + '/'}>
                          <a>{practicesItems[8]}</a>
                        </Link>
                      </li>
                    </ul>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/towns/' + lang + '/'}>
                      <a>{menuItems[3]}</a>
                    </Link>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/business-solutions/' + lang + '/'}>
                      <a>{menuItems[4]}</a>
                    </Link>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/towns/' + lang + '/'}>
                      <a>{menuItems[5]}</a>
                    </Link>
                  </li>
                  <li className='menu__item'>
                    <Link href={'/contacts/kyiv/' + lang + '/'}>
                      <a>{menuItems[6]}</a>
                    </Link>
                    <ul className='sub-menu'>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/kyiv/' + lang + '/'}>
                          <a>{offices[0]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/kharkiv/' + lang + '/'}>
                          <a>{offices[1]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/odessa/' + lang + '/'}>
                          <a>{offices[2]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/dnipro/' + lang + '/'}>
                          <a>{offices[3]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/zaporizhzhia/' + lang + '/'}>
                          <a>{offices[4]}</a>
                        </Link>
                      </li>
                      <li className='menu__item sub-menu__item'>
                        <Link href={'/contacts/kryviy-rih/' + lang + '/'}>
                          <a>{offices[5]}</a>
                        </Link>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
              <div className='menu__button'>
                <Link href='#'>
                  <a className='menu__button-link consult-btn'>{consultButton}</a>
                </Link>
              </div>
            </div>
          </nav>
        </section>
      </header>
    </>
  )
}
